# -*- coding: utf-8 -*-
"""test_for_import.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDoq8tW3Wfzgy_aEJDnVoGgL0woFyePB
"""

import numpy as np

def CheckFun(Input):
  if Input > 0.5
    print("Number above 0.5")
  else
    print("Number is not above 0.5")